{{- if .Values.backupServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vaultwarden_backup.backupServiceAccountName" . }}
  namespace: {{ include "vaultwarden_backup.namespace" . }}
  labels:
    {{- include "vaultwarden_backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
  {{- with .Values.backupServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.backupServiceAccount.automount }}
{{- end }}
