{{- if and .Values.vaultwarden.enabled .Values.vaultwarden.persistence.enabled (not .Values.vaultwarden.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden_backup.pvcName" . }}
  namespace: {{ include "vaultwarden_backup.namespace" . }}
  labels:
    {{- include "vaultwarden_backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- toYaml .Values.vaultwarden.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.vaultwarden.persistence.size }}
  {{- with .Values.vaultwarden.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
