{{- if .Values.backupCronJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vaultwarden_backup.backupCronJobName" . }}
  namespace: {{ include "vaultwarden_backup.namespace" . }}
  labels:
    {{- include "vaultwarden_backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets/scale"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vaultwarden_backup.backupCronJobName" . }}
  namespace: {{ include "vaultwarden_backup.namespace" . }}
  labels:
    {{- include "vaultwarden_backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
subjects:
  - kind: ServiceAccount
    name: {{ include "vaultwarden_backup.backupServiceAccountName" . }}
    namespace: {{ include "vaultwarden_backup.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vaultwarden_backup.backupCronJobName" . }}
{{- end }}
