{{- if .Values.backupCronJob.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backupCronJob.secret.name }}
  namespace: {{ include "vaultwarden_backup.namespace" . }}
  labels:
    {{- include "vaultwarden_backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
type: Opaque
stringData:
  rclone.conf: |
    [{{ .Values.webdav.remoteName }}]
    type = {{ .Values.webdav.type }}
    url = {{ .Values.webdav.url }}
    vendor = {{ .Values.webdav.vendor }}
    user = {{ .Values.webdav.username }}
    pass = {{ .Values.webdav.password }}
{{- end }}
---
{{- if .Values.restic.passwordSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.restic.passwordSecret.name }}
  namespace: {{ include "vaultwarden_backup.namespace" . }}
  labels:
    {{- include "vaultwarden_backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: restic
type: Opaque
stringData:
  {{ .Values.restic.passwordSecret.key }}: {{ .Values.restic.passwordSecret.value | quote }}
{{- end }}
