{{- if .Values.vaultwarden.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: vaultwarden
  {{- with .Values.vaultwarden.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.vaultwarden.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.vaultwarden.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.vaultwarden.domains }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.vaultwarden.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range .Values.vaultwarden.domains }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.vaultwarden.ingress.path }}
            pathType: {{ $.Values.vaultwarden.ingress.pathType }}
            backend:
              service:
                name: {{ include "helm.fullname" $ }}
                port:
                  number: {{ $.Values.vaultwarden.service.port }}
    {{- end }}
{{- end }}
