{{- if .Values.rclone.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rclone.secret.name }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
type: Opaque
stringData:
  rclone.conf: |
{{ .Values.rclone.secret.content | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.resticEnvSecretName" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
type: Opaque
stringData:
  RESTIC_PASSWORD: {{ .Values.vaultwardenRestic.env.RESTIC_PASSWORD | quote }}
  RESTIC_PASSWORD_FILE: {{ .Values.vaultwardenRestic.env.RESTIC_PASSWORD_FILE | quote }}
  RESTIC_REPOSITORY: {{ .Values.vaultwardenRestic.env.RESTIC_REPOSITORY | quote }}
  HOST_TAG: {{ .Values.vaultwardenRestic.env.HOST_TAG | quote }}
  BACKUP_TAG: {{ .Values.vaultwardenRestic.env.BACKUP_TAG | quote }}
  SCALE_DOWN_TIMEOUT_SECONDS: {{ .Values.vaultwardenRestic.env.SCALE_DOWN_TIMEOUT_SECONDS | quote }}
  SCALE_DOWN_POLL_INTERVAL_SECONDS: {{ .Values.vaultwardenRestic.env.SCALE_DOWN_POLL_INTERVAL_SECONDS | quote }}
  VAULTWARDEN_NAMESPACE: {{ .Release.Namespace | quote }}
  VAULTWARDEN_STATEFULSET: {{ include "helm.vaultwardenName" . | quote }}
  VW_DATA_DIR: {{ .Values.vaultwarden.persistence.mountPath | quote }}
  RCLONE_CONFIG: {{ .Values.rclone.configPath | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.archiveEnvSecretName" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: archive
type: Opaque
stringData:
  SOURCE_REMOTE_PATH: {{ .Values.vaultwardenArchive.env.SOURCE_REMOTE_PATH | quote }}
  TARGETS: {{ .Values.vaultwardenArchive.env.TARGETS | quote }}
  TARGET_PATH_PREFIX: {{ .Values.vaultwardenArchive.env.TARGET_PATH_PREFIX | quote }}
  RCLONE_CONFIG: {{ .Values.rclone.configPath | quote }}
